### PR TITLE
Set up PHP_CodeSniffer and WordPress-specific code sniffs.

### LINKED ISSUE #139: Add PHP_Codesniffer/WPCS
Code scanning tools could be very helpful:

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards

### PR DESCRIPTION
**Pull request by zamoose**
* [x] @zamoose
* [x] @markkelnar 

Fixes #139.

### CODE REVIEW

**Comment by markkelnar** [comment]
I like having this.  Question. these don't seem to be specific to nor depend on the php-fpm, would it make sense to not put the tasks in this role but in 'common' for example?

**Comment by zamoose** [comment]
It could be, though we're handling most of the PHP-specific stuff in that role. (E.g., PECL and PEAR installations, PHP-specific packages.)

Would you suggest moving that stuff out too, or...?

**Comment by markkelnar** [comment]
Probably one day these should not be in the php-fpm role since the WordPress-Coding-Standards and code-sniffer are tools added to the vagrant for development and not specific to PHP-FPM.

**Comment by zamoose** [comment]
I'm all for that, though I was viewing the role as less of an `-fpm` and more of a `php` sort of affair. I dropped e.g. the PECL and PEAR stuff into this role since we're already doing PHP-related dependencies related to FPM and friends.

**Comment by markkelnar** [comment]
Yep, understood.

**Pull request merged**
