### PR TITLE
Switch to using uri module instead of subbing out for command.

### LINKED ISSUE #124: Create wp-config: intermittent template error
Host: Mac OS X Mavericks

`wordpress | Create wp-config for {{ enviro }}` fails intermittently.  The string it fails at changes each time it fails.

A second provisioning run helps 99% of the time.

```
==> hgv: TASK: [wordpress | Create wp-config for php] **********************************
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
```

### PR DESCRIPTION
**Pull request by zamoose**
* [x] @zamoose
* [x] @markkelnar 

Fixes #124.

### CODE REVIEW

**Comment by zamoose** [comment]
Going with `stdout` seems to induce occasional escaping failures in the template, such that provisioning runs will fail. This should be a bit escape-character-safer.

**Comment by kevcenteno** [comment]
I'm seeing intermittent errors with using the uri module as well...

**Comment by kevcenteno** [comment]
Although, I agree that using the uri module is a better approach for fetching the content

**Comment by zamoose** [comment]
@kevcenteno Hmmm, same class of errors? Do you have a log dump of it?

**Comment by kevcenteno** [comment]
Actually, I was looking at the wrong provision run!  This looks good... and it's funny because I was on the same path :smile: 

vim

**Comment by kevcenteno** [comment]
Wait, I just got a debug error:

```
==> hgv-fork: TASK: [wordpress | debug var=wp_salt] *****************************************
==> hgv-fork: fatal: [127.0.0.1] => template error while templating string: unexpected char u'#' at 354
```

**Comment by zamoose** [comment]
I switched to use .content instead of .stdout in the template -- that seems
to have made a difference for me.

On Thu, Apr 16, 2015 at 10:00 AM, Kevin Centeno <notifications@github.com>
wrote:

> Wait, I just got a debug error:
>
> ==> hgv-fork: TASK: [wordpress | debug var=wp_salt] *****************************************
> ==> hgv-fork: fatal: [127.0.0.1] => template error while templating string: unexpected char u'#' at 354
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/pull/129#issuecomment-93741361>.
>



-- 
-Doug

**Comment by kevcenteno** [comment]
I'm also using .content in the template

**Pull request merged**
