### PR TITLE
Explicitly mark wp-config.php as Ansible-managed.

### LINKED ISSUE #156: Existing WP with wp-config.php failing vagrant up
When copy files for an existing WP install into hgv_data/sites/hhvm/ that contains wp-config.php, the wordpress.yml task that uses wp-cli to check 'core is-installed'.  Encounters an error connecting to mysql db using the existing db creds in the wp-config.php that was not provided by HGV, therefore does not contain the condition to use the HGV provided local-config.php file.

```
==> hgv: TASK: [wordpress | Check whether the WP install has been run previously] ******
...
==> hgv: <h1>Error establishing a database connection</h1>
==> hgv: <p>This either means that the username and password information in your <code>wp-config.php</code> file is incorrect or we can't contact the database server at <code>127.0.0.1</code>. This could mean your host's database server is down.</p>
==> hgv: <ul>
==> hgv: 	<li>Are you sure you have the correct username and password?</li>
==> hgv: 	<li>Are you sure that you have typed the correct hostname?</li>
==> hgv: 	<li>Are you sure that the database server is running?</li>
==> hgv: </ul>
==> hgv: <p>If you're unsure what these terms mean you should probably contact your host. If you still need help you can always visit the <a href='https://wordpress.org/support/'>WordPress Support Forums</a>.</p>

### PR DESCRIPTION
**Pull request by zamoose**
* [x] @zamoose
* [x] @markkelnar 

If the managed string isn't detected, re-template the file and save a backup copy.

Fixes #156.

### CODE REVIEW

**Comment by markkelnar** [comment]
Updating to let you know I'm testing this.  By first pass, looks like the right thing to use and I was quick to ok.  But wanted to test because I believe the default of use of the ansible_managed variable is not idempotent.  Maybe this won't be an issue because of the condition checks, but wanted to verify.

**Comment by zamoose** [comment]
Mark:
Alas, it is not idempotent:

https://github.com/ansible/ansible/issues/5317

Let's make it another variable that we define and just drop it in, say, `{{ hgv_managed }}` or somesuch.

**Comment by markkelnar** [comment]
Yes, works as you've initially coded. because your grep matches a smaller string of the ansible managed string.  I'll check my box and let you merge when you're happy of if you want to change it.

**Comment by zamoose** [comment]
I'm good to go. Let's merge it.

**Pull request merged**
