### PR TITLE
I don't think subliceasable is a word

### PR DESCRIPTION
**Pull request by michaelbeil**
:)

### CODE REVIEW

**Comment by zamoose** [comment]
Heh. 
screen shot 2015-04-13 at 2 17 07 pm

**Comment by michaelbeil** [comment]
how about that?! new words come from hgv.

**Comment by zamoose** [comment]
* [x] @zamoose
* [ ] @markkelnar 

I'm good to merge, although [IANALBIPOOTV](http://www.acronymfinder.com/I-Am-Not-A-Lawyer-But-I-Play-One-On-TV-(IANALBIPOOTV).html)

**Comment by zamoose** [comment]
For our intensive purposes, "subliceasable" is a perfectly cromulent word.

**Comment by michaelbeil** [comment]
perhaps you are going for a new way of obtaining lice?

**Pull request merged**
