### PR TITLE
Use latest ansible installation instructions

### PR DESCRIPTION
**Pull request by markkelnar**
New endpoints for more recent versions of ansible releases.

Fixes this issue https://github.com/wpengine/hgv/issues/77

 - [x] @markkelnar
 - [x] @zamoose 

* Let's hold off on merging this yet.  I want to do some more testing.

### CODE REVIEW

**Comment by zamoose** [comment]
I would push back on this and do a version check on Ansible before committing to an Apt run so as to make sure we're moving through quickly enough. Other than that, no objections.

**Comment by zamoose** [comment]
(To use the word of the day, let's make this action idempotent.)

**Comment by markkelnar** [comment]
Version checking based on what information?  Something from dpkg or apt-search?  How do you determine the latest version of the package before the apt run?  Also, the apt command will not re-install the apt package once the latest in installed.

Because these are in the bash script, idempotency within that script is a bit messy, and we need the latest ansible before any of our ansible playbooks are invoked.  

If we use ansible tasks to make sure we're on the lastest version, we'd need to run that as a separate ansible playbook, not part of our playbook.yml.  I'm up for reverting this bash script and making another yml playbook that does this.

**Comment by zamoose** [comment]
I'd say we have a minimum version as a variable inside the script,
`ANSIBLE_VER=1.7` or something, then do a `dpkg` + `-lt` and run the Apt
transaction only if it comes back as true.

On Wed, Feb 11, 2015 at 10:59 AM, Mark Kelnar <notifications@github.com>
wrote:

> Version checking based on what information? Something from dpkg or
> apt-search? How do you determine the latest version of the package before
> the apt run? Also, the apt command will not re-install the apt package once
> the latest in installed.
>
> Because these are in the bash script, idempotency within that script is a
> bit messy, and we need the latest ansible before any of our ansible
> playbooks are invoked.
>
> If we use ansible tasks to make sure we're on the lastest version, we'd
> need to run that as a separate ansible playbook, not part of our
> playbook.yml. I'm up for reverting this bash script and making another yml
> playbook that does this.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/wpengine/hgv/pull/78#issuecomment-73906058>.
>



-- 
-Doug

**Comment by zamoose** [comment]
Ansible being stuck at 1.5.3 is causing e.g. #90. I'd say we go ahead and push this in and perhaps push out a 1.1.1 or similar soon, as it's a regression. (I've confirmed it on a fresh pull and fresh VM.)

I retract my objections out of sheer practicality and expediency at the moment. *grin*

**Comment by markkelnar** [comment]
Fun.  Ok, I'll get on that circle back around with details/questions.

**Pull request merged**
