### PR TITLE
Enable Customfile Overrides

### LINKED ISSUE #197: Allow overrides to the Vagrant configuration, similar to VVV
VVV has had the ability for some time now to create a file named `Customfile`. This file will be parsed by the Vagrantfile as Ruby, and allows for overriding some of the default configurations.

For example, placing the following code into the `Customfile` will configure the VVV Vagrant with public networking, without the need to modify the `Vagrantfile` directly:

```ruby
  # Set up with a Public network
  config.vm.network :public_network
```

It would be nice to see something similar in hgv, and even better if it could somehow be implemented in a YAML file instead of a Ruby file. The YAML file could be in a pre-defined location, such as `hgv_data/config/vagrant/custom.yml`.

I'm not well-versed enough in Ruby to know exactly how to go about doing the YAML implementation that I described above, otherwise I would submit a PR.

On a related note, it might make more sense to divide the the `hgv_data/config/` directory into sub-directories, instead of *only* having site files there. Maybe something like this:

```
+ hgv_data/
|      + config/
|      |      + sites/
|      |      |      foo.yml
|      |      |      bar.yml
|      |      + vagrant/
|      |      |      custom.yml
```

### PR DESCRIPTION
**Pull request by ericmann**
- [x] @markkelnar
- [x] @ericmann

Utilize the same `Customfile` setup that powers runtime configuration
changes in [VVV](https://github.com/Varying-Vagrant-Vagrants/VVV). Placing
a `Customfile` in the root of the HGV installation will allow developers
to override specific configuration options, add extra providers, inject
additional provisioning steps, etc.

Fixes #197.

### CODE REVIEW

**Comment by zamoose** [comment]
Why not put it in `hgv_data/`?

**Comment by ericmann** [comment]
No particular reason not to. You could argue it's cleaner to keep Vagrantfile-type content in the same place. You could also argue it's cleaner to keep all Git-ignored configuration files in `/hgv_data`. It's more a personal preference than anything else here, and as `Customfile` applies to the VM itself and not any of the sites hosted by HGV, I felt the root was a better fit.

**Comment by markkelnar** [comment]
I can get behind either location.  It could be something specific to the stuff running within the vagrant or maybe a fix specific to the native environment.  Could argue either way.  As a first move, I'm cool with approving as it is at the top level directory.

**Comment by zamoose** [comment]
@ericmann @markkelnar I was advocating for locating the `Customfile` under `hgv_data/` so that customizations to HGV could be explicitly source-controlled by end users. As it stands now, there is no functional way to do so. Granted, it's a small file and probably easy to share, but making it safe for VCS would be a good step IMHO.

**Pull request merged**
