### PR TITLE
Add Serverspec testing

### PR DESCRIPTION
**Pull request by miya0001**
Add Serverspec testing.
https://github.com/wpengine/hgv/issues/60

```
$ bundle install --path vendor/bundler
$ bundle exec rake spec
```

Example:
```
$ bundle exec rake spec

Host "hhvm.hgv.dev"
  should be resolvable
  should be reachable

Host "php.hgv.dev"
  should be resolvable
  should be reachable

Host "fpm.hgv.dev"
  should be resolvable
  should be reachable

Host "cache.hhvm.hgv.dev"
  should be resolvable
  should be reachable

Host "cache.php.hgv.dev"
  should be resolvable
  should be reachable

Host "cache.fpm.hgv.dev"
  should be resolvable
  should be reachable

Host "admin.hgv.dev"
  should be resolvable
  should be reachable

Host "xhprof.hgv.dev"
  should be resolvable
  should be reachable

Host "mail.hgv.dev"
  should be resolvable
  should be reachable

Service "nginx"
  should be enabled
  should be running

Service "mysql"
  should be enabled
  should be running

Service "hhvm"
  should be enabled
  should be running

Service "varnish"
  should be enabled
  should be running

Command "wget -q http://hgv.dev/ -O - | grep '<title>'"
  stdout
    should match /<title>WP Engine Mercury Vagrant<\/title>/

Command "wget -q http://hhvm.hgv.dev/ -O - | grep '<title>'"
  stdout
    should match /<title>WP Engine hhvm Site | Just another WordPress site<\/title>/

Command "wget -q http://php.hgv.dev/ -O - | grep '<title>'"
  stdout
    should match /<title>WP Engine php Site | Just another WordPress site<\/title>/

Command "wget -q http://admin.hgv.dev/ -O - | grep '<title>'"
  stdout
    should match /<title>Admin - WP Engine Mercury Vagrant<\/title>/

Command "wget -q http://admin.hgv.dev/phpmyadmin/ -O - | grep '<title>'"
  stdout
    should match /<title>phpMyAdmin<\/title>/

Command "wget -q http://admin.hgv.dev/phpmemcachedadmin -O - | grep '<title>'"
  stdout
    should match /<title>phpMemcachedAdmin.*?<\/title>/

Command "wget -q http://admin.hgv.dev/logs -O - | grep '<title>'"
  stdout
    should match /<title>Pimp my Log<\/title>/

Command "wp --path=/hgv_data/sites/hhvm plugin status akismet"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/hhvm plugin status debug-bar"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/hhvm plugin status debug-objects"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/hhvm plugin status debug-queries"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/hhvm plugin status hello"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/hhvm plugin status query-monitor"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/php plugin status akismet"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/php plugin status debug-bar"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/php plugin status debug-objects"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/php plugin status debug-queries"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/php plugin status hello"
  exit_status
    should eq 0

Command "wp --path=/hgv_data/sites/php plugin status query-monitor"
  exit_status
    should eq 0

Finished in 9.35 seconds (files took 7.5 seconds to load)
45 examples, 0 failures
```

### CODE REVIEW

**Comment by zamoose** [comment]
@miya0001 This is awesome. Thanks for the contribution. We may need to massage it a bit, but this is great.

**Comment by miya0001** [comment]
You're welcome.

This is our project and there is another example. :wink: 
https://github.com/vccw-team/vccw/tree/master/spec/default

**Comment by markkelnar** [comment]
Thanks @miya0001.  I'm going to pull this down and test it.  We might be able to get this in the next release.

**Comment by miya0001** [comment]
Great! Thanks!! +1

**Comment by stephen-lin** [comment]
Merging knowing that some things won't work out of the box, but so that we can expand it later.

**Pull request merged**
