### PR TITLE
Adjust spacing on the ANSI logo.

### PR DESCRIPTION
**Pull request by morganestes**
The logo spacing in `/bin/hgv-init.sh` is just a little off. This just lines things up better to satisfy my OCD.

 - [x] @markkelnar
 - [ ] @zamoose

### CODE REVIEW

**Comment by zamoose** [comment]
Removing the escaping of the backtick can cause the shell to error out. I'm thinking this one won't fly.

**Comment by morganestes** [comment]
Doh! Yeah, I missed that it was escaping and not just part of the text. I re-escaped the backtick and adjusted the spacing so everything else lines up.

**Comment by markkelnar** [comment]
@morganestes I played with this spacing before the initial release, for longer than I'd like to admit.  When I run your change, this is what it looks like, is this what you're expecting?  Note the other things on the line that don't line up anymore.

screen shot 2015-04-01 at 1 50 39 pm

**Comment by morganestes** [comment]
@markkelnar That's the first patch. The second one re-aligns the boxes and fixes the "V".
https://github.com/morganestes/hgv/commit/73959ec5d97164e4721802f897e240644ef7ea66

screencapture at wed apr 1 21 41 49 cdt 2015

**Comment by markkelnar** [comment]
But when the bash script runs and echos the ascii art to stdout, you'll see something like in my attachment above.  To recreate, run the script bin/hgv-init.sh and you should see what I'm talking about.

**Comment by morganestes** [comment]
@markkelnar I missed that it displayed differently based on whether it was running or just printed out. :/

I removed the backtick completely and ran the script. It runs and looks straight now.
screencapture at thu apr 2 12 22 44 cdt 2015

**Comment by michaelbeil** [comment]
OCD FTW!

**Pull request merged**
