### PR TITLE
Replace the problematic character sequences so Jinja2 doesn't freak out.

### LINKED ISSUE #124: Create wp-config: intermittent template error
Host: Mac OS X Mavericks

`wordpress | Create wp-config for {{ enviro }}` fails intermittently.  The string it fails at changes each time it fails.

A second provisioning run helps 99% of the time.

```
==> hgv: TASK: [wordpress | Create wp-config for php] **********************************
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
==> hgv: fatal: [127.0.0.1] => {'msg': "AnsibleError: template error while templating string: unexpected '|'", 'failed': True}
```

### PR DESCRIPTION
**Pull request by zamoose**
* [ ] @zamoose
* [ ] @markkelnar 

Filter twice at wp-config.php creation time. Fixes #124. (For real, this time.)

### CODE REVIEW

**Comment by zamoose** [comment]
@kevcenteno Try this fix out and see if it works for you.

**Comment by kevcenteno** [comment]
I executed a bunch of runs and got 2 failures.  Luckily, Ansible spat out some sensible debug data!

Fail #1:
```
==> hgv-fork: TASK: [wordpress | Create wp-config for hhvm] *********************************
==> hgv-fork: fatal: [127.0.0.1] => {'msg': "AnsibleError: Failed to template define('AUTH_KEY',         'ZfdVr oaH{{zDD{IP:,X=g@cH8wg2(|et:pe3+||l+ tl%.&TB|IL2xH5=rSZ,oz');\ndefine('SECURE_AUTH_KEY',  'JJn*8ACN4 &haR,~6qS~VnQ9G.9hRlZHWW6,B.}3-z|-I6a|4|3dB}3^,*f:HZ<q');\ndefine('LOGGED_IN_K
EY',    '=q#j2PQl2xT}H^4|n_0a,AI~(2CBf^AvPw/1^w%+*mY^C>8~(pleO wZF,6(73+;');\ndefine('NONCE_KEY',        'K+sj=!TLtkz4dS&|8p=Y$H|-WvxgDnjgtnMY(h0LrOq_PWbHAgt@-ktp;;)?R9v-');\ndefine('AUTH_SALT',        '+ds[}^s8^d}#XB(.|X+xEc?b`X<gbij^;/^RkW!3N)s45KO5+Id_=0TJ)(wsIgIw');\ndefine('SECURE_AUTH
_SALT', '!t]k$d6p^b:UO[#;*A>wcem/3s=86<5=<*@H/e-F}cU[j]i+(pRs8F5Bf~oUL|6-');\ndefine('LOGGED_IN_SALT',   'D9]/_GtS(p?{1Gj.Z[u%b+}(fO7Fb_BNm-s%709!0Nutd=:+>>j9/$Bjgkh,ce2W');\ndefine('NONCE_SALT',       'YR66%]|7_L%A-Bt@D+.<=;1Z5<8*w~h5cI&RXJg@j:N?CYz0 ]f$-bC%oBV7*+LE');\n: template error wh
ile templating string: expected token 'end of print statement', got '{'", 'failed': True}
==> hgv-fork: fatal: [127.0.0.1] => {'msg': "AnsibleError: Failed to template define('AUTH_KEY',         'ZfdVr oaH{{zDD{IP:,X=g@cH8wg2(|et:pe3+||l+ tl%.&TB|IL2xH5=rSZ,oz');\ndefine('SECURE_AUTH_KEY',  'JJn*8ACN4 &haR,~6qS~VnQ9G.9hRlZHWW6,B.}3-z|-I6a|4|3dB}3^,*f:HZ<q');\ndefine('LOGGED_IN_K
EY',    '=q#j2PQl2xT}H^4|n_0a,AI~(2CBf^AvPw/1^w%+*mY^C>8~(pleO wZF,6(73+;');\ndefine('NONCE_KEY',        'K+sj=!TLtkz4dS&|8p=Y$H|-WvxgDnjgtnMY(h0LrOq_PWbHAgt@-ktp;;)?R9v-');\ndefine('AUTH_SALT',        '+ds[}^s8^d}#XB(.|X+xEc?b`X<gbij^;/^RkW!3N)s45KO5+Id_=0TJ)(wsIgIw');\ndefine('SECURE_AUTH
_SALT', '!t]k$d6p^b:UO[#;*A>wcem/3s=86<5=<*@H/e-F}cU[j]i+(pRs8F5Bf~oUL|6-');\ndefine('LOGGED_IN_SALT',   'D9]/_GtS(p?{1Gj.Z[u%b+}(fO7Fb_BNm-s%709!0Nutd=:+>>j9/$Bjgkh,ce2W');\ndefine('NONCE_SALT',       'YR66%]|7_L%A-Bt@D+.<=;1Z5<8*w~h5cI&RXJg@j:N?CYz0 ]f$-bC%oBV7*+LE');\n: template error wh
ile templating string: expected token 'end of print statement', got '{'", 'failed': True}
==> hgv-fork:
==> hgv-fork: FATAL: all hosts have already failed -- aborting
```

Fail #1:
```
==> hgv-fork: TASK: [wordpress | Create wp-config for hhvm] *********************************
==> hgv-fork: fatal: [127.0.0.1] => {'msg': "AnsibleError: Failed to template define('AUTH_KEY',         ']s%>r+zlM!MQkyiv|wDsi[JQ-x&}(QLSotfdL4uI0V3!l!r^o;7{XEZ4dN=Dp7Jr');\ndefine('SECURE_AUTH_KEY',  '@OS @Q:h;?pKYFg&Yt#$* < UpUOGzl.`k;l,)]~Irb^Wd_}d/|y:>IOi`uYENV]');\ndefine('LOGGED_IN_KEY',    '|gN10:Tn ,~>YrxF^:{}]#H2J$V+E+exwh039HW-/gw.4YWzWo@|iFdfl%@Ef7:$');\ndefine('NONCE_KEY',        ',}c?csQ`d;4-SF2T}{{1[Kwp],[_w9Er_~x$OKGRyEnDae/:>VaE${2u|biD3._n');\ndefine('AUTH_SALT',        'k2YukX?V7&U#O]Uz2F|~|{$zi0,_<}sj8sXjE7!.V[fb8&N}@5@f)#M! D,}ds+)');\ndefine('SECURE_AUTH_SALT', 'v4+nVIp*:^3?Ov3{Y$_H~_- |+`AVZU}UZo(xe)1|+0Z;LAY{Ce<d];VOIq%WIEL');\ndefine('LOGGED_IN_SALT',   '9-Swxa!s,#1q}TF92z@1}Wa;wTxom:-a<Nz Tb~U+A^x|-DO6ePn?vF:+:^RG=ST');\ndefine('NONCE_SALT',       'gnn>-y`Ug[V:{F<%)qM ZqO5YYAuPa/GxUJw7:XUmRv$8hS5A.c:iRJl.frJX_#-');\n: template error while templating string: unexpected char u'$' at 351", 'failed': True}
==> hgv-fork: fatal: [127.0.0.1] => {'msg': "AnsibleError: Failed to template define('AUTH_KEY',         ']s%>r+zlM!MQkyiv|wDsi[JQ-x&}(QLSotfdL4uI0V3!l!r^o;7{XEZ4dN=Dp7Jr');\ndefine('SECURE_AUTH_KEY',  '@OS @Q:h;?pKYFg&Yt#$* < UpUOGzl.`k;l,)]~Irb^Wd_}d/|y:>IOi`uYENV]');\ndefine('LOGGED_IN_KEY',    '|gN10:Tn ,~>YrxF^:{}]#H2J$V+E+exwh039HW-/gw.4YWzWo@|iFdfl%@Ef7:$');\ndefine('NONCE_KEY',        ',}c?csQ`d;4-SF2T}{{1[Kwp],[_w9Er_~x$OKGRyEnDae/:>VaE${2u|biD3._n');\ndefine('AUTH_SALT',        'k2YukX?V7&U#O]Uz2F|~|{$zi0,_<}sj8sXjE7!.V[fb8&N}@5@f)#M! D,}ds+)');\ndefine('SECURE_AUTH_SALT', 'v4+nVIp*:^3?Ov3{Y$_H~_- |+`AVZU}UZo(xe)1|+0Z;LAY{Ce<d];VOIq%WIEL');\ndefine('LOGGED_IN_SALT',   '9-Swxa!s,#1q}TF92z@1}Wa;wTxom:-a<Nz Tb~U+A^x|-DO6ePn?vF:+:^RG=ST');\ndefine('NONCE_SALT',       'gnn>-y`Ug[V:{F<%)qM ZqO5YYAuPa/GxUJw7:XUmRv$8hS5A.c:iRJl.frJX_#-');\n: template error while templating string: unexpected char u'$' at 351", 'failed': True}
```

**Comment by kevcenteno** [comment]
It seems that it's still failing at `{{`

**Comment by zamoose** [comment]
This approach is problematic. I'm going to submit a new PR with a different approach.

**Pull request closed without merging**
