### PR TITLE
Feature/yaml start

### PR DESCRIPTION
**Pull request by ericmann**
- [x] @markkelnar
- [x] @ericmann

First pass at a YAML generation script.

## Coding approach

The startup script is written in JavaScript using NodeJS as a local script interpreter. The code is intended to use the latest version of Node (0.12.7 currently).

Modules used by the script are bundled into `/node_modules` so the end user never needs to run `npm install` on their own. We might need to revisit this in the future to minimize the size of the overall repository.

## Execution Details

From the root of the Mercury installation, run `script/start`. Scripts are set up to execute both on Mac and Windows. On Mac, the `/script/start` routine runs directly and executes against Node. On Windows, the `/script/start.cmd` routine forces Node to execute the underlying start script.

No command line parameters are required for a _new_ installation, and the script will generate a `.mercuryrc` file at the root of the installation.

If a configuration file already exists, the script will detect the file and abort unless the `--force` parameter is specified at the command line. In that case, the script will load the existing file as the defaults and allow the user to update any settings.

## Generated YAML file

The generated file takes the following format:

```yaml
wp:
  environ: foo
  hhvm_domains:
    - foo.test
    - www.foo.test
  php_domains:
    - php.foo.test
  # The name of the WP install on the WP Engine side
  wpe_name: bar
  # The git branch to push to by default
  branch: develop
  # The remote endpoint environment to push to by default (staging or production)
  remote: staging
```

The inline comments above are provided here for reference but will _not_ be included in the generated YAML file.

### CODE REVIEW

**Comment by zamoose** [comment]
I'm out of the loop here -- what does this end up providing? I think I see the beginnings of supporting `vagrant push`, which is awesome, but beyond that...?

**Comment by ericmann** [comment]
It's one of the first steps toward supporting `vagrant push`. We've got several sub-tasks built into that, and a few scripts that will need to run on the host machine to power the setup. This is but the first.

**Comment by zamoose** [comment]
Gotcha, cool.

**Comment by markkelnar** [comment]
Wow, that's a lot of files with that Node library.  But maybe that's the only way right now.  
What goes in that .mercuryrc file that's different than the WP config files in hgv_data/config/*.yml ?

**Comment by ericmann** [comment]
## Contents

Since the `/config` directory isn't created on provision, I completely missed that it was a thing (so the YAML above isn't entirely consistent and will need to change). For reference, the only data I have on any YAML files in that directory is the contents of default-install.yml:

```yaml
---
wp:
  enviro: hhvm
  hhvm_domains:
    - hhvm.hgv.dev
    - hhvm.hgv.test
  php_domains:
    - php.hgv.dev
    - php.hgv.test
```

In addition to `enviro`, `hhvm_domains`, and `php_domains`, the generated YAML file contains:

```yaml
  wpe_name: bar
  # The git branch to push to by default
  branch: develop
  # The remote endpoint environment to push to by default (staging or production)
  remote: staging
```

(Note: I need to update the generated file to use `enviro` instead of `environ` - this was a copy-paste error.)

## Node

I agree, the `node_modules` directory is quite large and I'd like to minimize it. Vagrant isn't very good at running scripts against the _host_ during provisioning, so there are only two ways to ship without modules bundled:

1. Force the provisioner to add Node within the VM and run `npm install --no-bin-link` against the mounted directory (this will download all of our packages on the host through the mounted filesystem)
1. Require the end user to run `npm install` after cloning Hgv. It's an added installation step, but is the safest way for us to ensure things are installed correctly.

I'm more a fan of the second option, but as it adds an installation step, I'm somewhat hesitant and want to leave it open to debate.

## Location

Since I wasn't in the loop regarding a `/config` directory for independent installations, everything is coded to be run at the root of the Hgv installation. We can easily rewrite this, but if we do I need some clarity on where things run and how they're meant to interact.

Running from the root to create a `.mercuryrc` file seemed like the best idea at the time if we were taking a one Hgv to one Mercury deployment route. If Hgv is hosting _multiple_ sites deployed then it makes far more sense to move things to a `/config` directory. The questions there then become:

- How do we run the command? Do we require end users to specify a configuration file with which they're working? As this is a generator, do we require someone provide a filename or do we assume a specific default? (As part of the requirements were to detect and warn if a config already existed, how does this change impact things?)
- How do we pair the config files with the sites elsewhere within `/hgv_data`? Is that done automatically, or do we need to parse configuration files when things run?
- Does the command need to run from _anywhere_ within the Hgv install, from just within the `/hgv_data/config` directory, or from within specific site directories?

**Comment by markkelnar** [comment]
The /config/ directory was designed as a placeholder for the end user to add, maintain, manage, share HGV YAML formatted files that map to the WP they are working on in the hgv_data/sites/ directory.  And those files are used during the vagrant provisioning (bin/custom-sites.sh) run.  See that file for the wildcard glob (/vagrant/hgv_data/config/*.yml) of where/when/how .yml files in config/ can be used right now. 

Also, if we need to modify or define the layout of the config/ directory, let's do that.  If we see any issues with that *.yml glob, let's fix that as needed so it's more robust for the long term.

a) We don't have a naming convention requirement of the .yml file.  I need to get back with you on the other parts of this first question.

b) The 'enviro' variable identifies the docroot of the WP the file is paired with.  (@zamoose and I had many discussions about renaming that variable to something more meaningful and just couldn't name it down)

c) I was thinking the top level where the vagrant command is run.  And the command would need to know the name of the docroot/enviro or the yaml file name.  Thinking we could pass that on command line.

**Comment by ericmann** [comment]
OK, this is good to go. The bug I was chasing down turned out to be due to an outdated Node installation (I was running 0.10.40 for legacy dev purposes on another project. Under 0.12.X everything works as expected).

**Pull request merged**
